[package]
name = "doc-simfinder"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.51"
fuzzy-matcher = "0.3.7"
globset = "0.4.18"
inquire = "0.9.1"
rayon = "1.11.0"
tempfile = "3.23.0"
thiserror = "2.0.17"
walkdir = "2.5.0"
